name: pytest-coverage-comment
on:
  pull_request:
    branches:
      - '*'

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Pytest coverage
        id: run_pytest
        run: |
          cd backend
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=app tests/ | tee pytest-coverage.txt
          exit_code=${PIPESTATUS[0]}
          echo "Pytest exit code: $exit_code"
          echo "pytest_exit_code=$exit_code" >> $GITHUB_OUTPUT

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./backend/pytest-coverage.txt
          junitxml-path: ./backend/pytest.xml
          coverage-path-prefix: ./backend/

      - name: Fail if pytest fails
        if: steps.run_pytest.outputs.pytest_exit_code != '0'
        run: exit 1
